version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: Rooter@2389
      MYSQL_DATABASE: crud_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  crud-app:
    build: .
    container_name: crud-container
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/crud_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Rooter@2389

  frontend:
    build: ../../frontend/crudfront
    container_name: frontend-container
    ports:
      - "3000:3000"
    depends_on:
      - crud-app
    environment:
      REACT_APP_API_URL: http://localhost:8080

volumes:
  mysql_data: